### PR TITLE
templates/facts.rb.erb: update URI.open syntax to fix deprecation warnings

### LINKED ISSUE #330: Jira_facts deprecation warnings
# Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.18.0
- Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) 
- Distribution: Ubuntu 20.04
- Module version: 4.0.1

## How to reproduce (e.g Puppet code you use)

```
class { 'jira::facts': }
```
## What are you seeing

```
Warning: Facter: external fact file "/etc/facter/facts.d/jira_facts.rb" had output on stderr: /etc/facter/facts.d/jira_facts.rb:17: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
```
## What behaviour did you expect instead

No warnings

## Output log

```
Warning: Facter: external fact file "/etc/facter/facts.d/jira_facts.rb" had output on stderr: /etc/facter/facts.d/jira_facts.rb:17: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
Info: Using configured environment 'CustomerInfra'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Warning: Facter: external fact file "/etc/facter/facts.d/jira_facts.rb" had output on stderr: /etc/facter/facts.d/jira_facts.rb:17: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
Info: Caching catalog for jira01-qual.node.customer.cloud
Notice: Applied catalog in 14.88 seconds
```

### PR DESCRIPTION
**Pull request by kenyon**
templates/facts.rb.erb: update URI.open syntax to fix deprecation warnings

Fixes #330.

### CODE REVIEW

File: templates/facts.rb.erb [hunk 1]
```diff
@@ -14,7 +14,7 @@ require 'json'
 require 'open-uri'
```
Comment (ekohl) [inline templates/facts.rb.erb:14]: Is this require still correct?
```suggestion
require 'uri'
```

**Review by ekohl — APPROVED** [review]
